import * as pdfjsLib from "https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.mjs";
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.worker.mjs";
let pdf=null,index=0,tasks=[];
const spreads=[[1],[2,3],[4,5],[6,7],[8,9],[10,11],[12,13],[14,15],[16]];
const wrap=document.querySelector("#spreadWrap"),left=document.querySelector("#leafLeft"),right=document.querySelector("#leafRight"),status=document.querySelector("#pdfStatus"),label=document.querySelector("#spreadLabel"),meta=document.querySelector("#pageNow");
async function draw(num,canvas,leaf){if(!num){leaf.classList.add("hidden");return}leaf.classList.remove("hidden");const pg=await pdf.getPage(num),base=pg.getViewport({scale:1}),rect=leaf.getBoundingClientRect(),scale=Math.min(rect.width/base.width,rect.height/base.height),vp=pg.getViewport({scale}),dpr=Math.min(devicePixelRatio||1,2),ctx=canvas.getContext("2d");canvas.width=Math.floor(vp.width*dpr);canvas.height=Math.floor(vp.height*dpr);canvas.style.width=vp.width+"px";canvas.style.height=vp.height+"px";const task=pg.render({canvasContext:ctx,viewport:vp,transform:dpr!==1?[dpr,0,0,dpr,0,0]:null});tasks.push(task);try{await task.promise}catch(e){if(e?.name!=="RenderingCancelledException")throw e}}
async function render(i){index=Math.max(0,Math.min(spreads.length-1,i));tasks.forEach(t=>{try{t.cancel()}catch(e){}});tasks=[];const s=spreads[index],single=s.length===1;wrap.classList.toggle("single-spread",single);if(single){left.classList.remove("hidden");right.classList.add("hidden");await draw(s[0],document.querySelector("#canvasLeft"),left)}else{await Promise.all([draw(s[0],document.querySelector("#canvasLeft"),left),draw(s[1],document.querySelector("#canvasRight"),right)])}meta.textContent=s.length===1?s[0]+" / "+pdf.numPages:s[0]+"–"+s[1]+" / "+pdf.numPages;label.textContent=index===0?"COVER":index===spreads.length-1?"BACK COVER":"OPEN GUIDE";status.classList.add("hidden")}
async function load(){let err;for(const src of ["/Beachcomber.pdf","https://raw.githubusercontent.com/str1-ops/Strictons/main/Beachcomber.pdf"]){try{pdf=await pdfjsLib.getDocument({url:src}).promise;await render(0);return}catch(e){err=e}}status.textContent="Guide could not be loaded";console.error(err)}load();
document.querySelector("#prevPage").onclick=()=>render(index-1);document.querySelector("#nextPage").onclick=()=>render(index+1);wrap.addEventListener("click",e=>{if(e.clientX<innerWidth/2)render(index-1);else render(index+1)});addEventListener("keydown",e=>{if(e.key==="ArrowLeft")render(index-1);if(e.key==="ArrowRight")render(index+1)});let rt;addEventListener("resize",()=>{clearTimeout(rt);rt=setTimeout(()=>pdf&&render(index),140)});
const header=document.querySelector("#siteHeader"),openBtn=document.querySelector("#menuOpen"),overlay=document.querySelector("#menuOverlay");function setHeader(){header.classList.toggle("scrolled",scrollY>1)}addEventListener("scroll",setHeader,{passive:true});setHeader();function menu(open){if(open){overlay.classList.remove("closing");overlay.classList.add("open");overlay.setAttribute("aria-hidden","false");openBtn.setAttribute("aria-expanded","true");document.body.classList.add("menu-open")}else if(overlay.classList.contains("open")){overlay.classList.remove("open");overlay.classList.add("closing");overlay.setAttribute("aria-hidden","true");openBtn.setAttribute("aria-expanded","false");setTimeout(()=>{overlay.classList.remove("closing");document.body.classList.remove("menu-open")},300)}}openBtn.addEventListener("click",()=>menu(!overlay.classList.contains("open")));overlay.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>menu(false)));document.querySelector(".site-header .wordmark")?.addEventListener("click",()=>menu(false));addEventListener("keydown",e=>{if(e.key==="Escape")menu(false)});