const spreads=[[1],[2,3],[4,5],[6,7],[8,9],[10,11],[12,13],[14,15],[16]];
const images=new Map();let index=0,busy=false;
const spread=document.querySelector("#bookSpread"),left=document.querySelector("#leftPage"),right=document.querySelector("#rightPage"),loading=document.querySelector("#bookLoading"),prev=document.querySelector("#prevPage"),next=document.querySelector("#nextPage"),dots=document.querySelector("#bookDots");
const src=n=>"/assets/showcase/page-"+String(n).padStart(2,"0")+".jpg";
function load(n){if(images.has(n))return images.get(n);const p=new Promise((resolve,reject)=>{const im=new Image();im.decoding="async";im.src=src(n);im.onload=async()=>{try{await im.decode()}catch(e){}resolve(im)};im.onerror=reject});images.set(n,p);return p}
async function prepare(i){const pages=spreads[i];if(!pages)return null;return {pages,imgs:await Promise.all(pages.map(load))}}
function place(el,im,alt){el.src=im.src;el.alt=alt;el.style.width="auto";el.style.height="100%"}
function updateDots(){if(!dots)return;[...dots.children].forEach((dot,i)=>dot.classList.toggle("active",i===index))}
function buildDots(){if(!dots)return;dots.innerHTML="";spreads.forEach((_,i)=>{const dot=document.createElement("span");dot.className="book-dot"+(i===0?" active":"");dot.setAttribute("aria-hidden","true");dots.appendChild(dot)})}
async function show(i){if(busy||i<0||i>=spreads.length||i===index)return;busy=true;try{const ready=await prepare(i),single=ready.pages.length===1;spread.classList.toggle("single",single);if(single){place(right,ready.imgs[0],ready.pages[0]===16?"Beachcomber guide back cover":"Beachcomber guide cover");left.removeAttribute("src")}else{place(left,ready.imgs[0],"Beachcomber guide page "+ready.pages[0]);place(right,ready.imgs[1],"Beachcomber guide page "+ready.pages[1])}index=i;prev.disabled=index===0;next.disabled=index===spreads.length-1;updateDots();[index-1,index+1,index+2].filter(x=>x>=0&&x<spreads.length).forEach(x=>prepare(x).catch(()=>{}))}finally{busy=false}}
async function init(){buildDots();try{const first=await prepare(0);place(right,first.imgs[0],"Beachcomber guide cover");spread.classList.add("single");prev.disabled=true;next.disabled=false;loading.classList.add("hidden");Promise.all([prepare(1),prepare(2),prepare(3)]).then(()=>{const rest=()=>Promise.all(spreads.slice(4).map((_,k)=>prepare(k+4))).catch(()=>{});"requestIdleCallback"in window?requestIdleCallback(rest,{timeout:1200}):setTimeout(rest,100)}).catch(()=>{})}catch(e){console.error(e);loading.classList.add("hidden")}}
prev.onclick=()=>show(index-1);next.onclick=()=>show(index+1);
let touchStartX=0,touchStartY=0,didSwipe=false;
spread.addEventListener("touchstart",e=>{const t=e.changedTouches[0];touchStartX=t.clientX;touchStartY=t.clientY;didSwipe=false},{passive:true});
spread.addEventListener("touchend",e=>{const t=e.changedTouches[0],dx=t.clientX-touchStartX,dy=t.clientY-touchStartY;if(Math.abs(dx)>42&&Math.abs(dx)>Math.abs(dy)*1.25){didSwipe=true;show(index+(dx<0?1:-1))}},{passive:true});
spread.onclick=e=>{if(didSwipe){didSwipe=false;return}if(matchMedia("(max-width:850px)").matches)return;show(index+(e.clientX<spread.getBoundingClientRect().left+spread.clientWidth/2?-1:1))};
addEventListener("keydown",e=>{if(e.key==="ArrowLeft")show(index-1);if(e.key==="ArrowRight")show(index+1)});
init();

const header=document.querySelector("#siteHeader"),openBtn=document.querySelector("#menuOpen"),overlay=document.querySelector("#menuOverlay");function setHeader(){header.classList.toggle("scrolled",scrollY>1)}addEventListener("scroll",setHeader,{passive:true});setHeader();function menu(open){if(open){overlay.classList.remove("closing");overlay.classList.add("open");overlay.setAttribute("aria-hidden","false");openBtn.setAttribute("aria-expanded","true");document.body.classList.add("menu-open")}else if(overlay.classList.contains("open")){overlay.classList.remove("open");overlay.classList.add("closing");overlay.setAttribute("aria-hidden","true");openBtn.setAttribute("aria-expanded","false");setTimeout(()=>{overlay.classList.remove("closing");document.body.classList.remove("menu-open")},300)}}openBtn.addEventListener("click",()=>menu(!overlay.classList.contains("open")));overlay.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>menu(false)));document.querySelector(".site-header .wordmark")?.addEventListener("click",()=>menu(false));addEventListener("keydown",e=>{if(e.key==="Escape")menu(false)});